[package]
name = "tokio-serge-json-server"
version = "0.1.0"
authors = ["Jason Vranek <jvranek@ucsc.edu>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-serde-json = "0.2"
serde_json = "1.0"
serde = "1.0"
tokio-serde = "0.3"